// finish
// start

const actionTypes = {
  START_FETCH_NOTIFICATION: 'START_FETCH_NOTIFICATION',
  START_NOTIFICATION_POST: 'START_NOTIFICATION_POST',
  FINISH_NOTIFICATION_POST: 'FINISH_NOTIFICATION_POST',
  // FETCH_NOTIFICATION_SUCCESS: 'FETCH_NOTIFICATION_SUCCESS',
  // FETCH_NOTIFICATION_FAIL: 'FETCH_NOTIFICATION_FAIL',
  MARK_NOTIFICATIONS_AS_READ_BY_ID: 'MARK_NOTIFICATIONS_AS_READ_BY_ID',
  MARK_ALL_NOTIFICATIONS_AS_READ: 'MARK_ALL_NOTIFICATIONS_AS_READ',
  FETCH_NOTIFICATIONS: 'FETCH_NOTIFICATIONS'
}

export default actionTypes
